### ISSUE TITLE
stringRep ends with '\r'

### ISSUE THREAD

**Issue by adamski** [surge-synthesizer/tuning-library#37]
With some `scl` files, I assume those with Windows/DOS line endings, `stringRep` contains a string ending with `\r`

[wilson5.scl.txt](https://github.com/surge-synthesizer/tuning-library/files/6300379/wilson5.scl.txt)

**Comment by baconpaul** [comment]
for now at least you can run `dos2unix` on that file and it should load fine. Presume you know that but in case you don't!

**Comment by adamski** [comment]
Sure, also easy to fix in our project using the library, just thought I'd report here in case you were not aware of it.

**Comment by baconpaul** [comment]
I was not! Appreciate the flag and will definitely think about how to fix. I guess just strop \r if they show up is the standard approach. Thank you!

**Comment by baconpaul** [comment]
Basically I need to replace std::getline with something more like this https://gist.github.com/josephwb/df09e3a71679461fc104

And then add your file to our test suite (presume you are OK if I do that but want to check!)

**Comment by adamski** [comment]
The file was taken from the zip file of scales from the Scala website.

**Comment by baconpaul** [comment]
Great. Turns out we already had a test dos le in our test set; I just only checked the parsing not the stripping.

PR and change coming shortly. I'll update surge also so it uses it before the 19 release.

**Comment by baconpaul** [comment]
OK fix in place along with expanding the test some. Thanks!

**Comment by baconpaul** [comment]
Oooh one more tweak coming. All our tests in tuning-lib pass with this change but one surge test is failing. Stay tuned!

**Comment by baconpaul** [comment]
Sneaky extra line at end of file check failed and we test that in surge tests but not tuning lib tests. All good to go now. Updating surge also.
