### ISSUE TITLE
test typos?

### ISSUE THREAD

**Issue by chinenual** [surge-synthesizer/tuning-library#50]
In the new tests for skipped notes, the "gaps" tests assert the modulo scale positions as midi notes - I suspect a typo:

```c++
        for (int k = 0; k < 128; ++k)
        {
            int i = k % 12;
            bool isOn = i == 0 || i == 2 || i == 4 || i == 5 || i == 7 || i == 
9 || i == 11;
            INFO(k << " scpos=" << i << " isOn = " << isOn);
            REQUIRE(t.isMidiNoteMapped(i) == isOn);
        }
```
was probably intended to test
```c++
            REQUIRE(t.isMidiNoteMapped(k) == isOn);
```
if so, there are similar typos in 
```
    SECTION("Gaps in the Maps")
    SECTION("Gaps in the Maps KBM Only")
    SECTION("Tuning with Gaps and Interpolation")
```

**Comment by baconpaul** [comment]
Oh ha yeah that is a typo good find. It happens to work since I am testing against a keyboard model which has periodicity 12 but the test would break otherwise. Thank you.

**Comment by baconpaul** [comment]
#51 will fix this .Will merge once CI is done (pipelines are a bit full with some builds I'm doing for surge proper right now). Great catch thank you.
