### ISSUE TITLE
Incorrect frequencies assigned for 31edo2 tuning and subset keyboard mapping

### ISSUE THREAD

**Issue by rcook** [surge-synthesizer/tuning-library#72]
**This is a cross-post from this bug https://github.com/surge-synthesizer/surge/issues/7822.**

**Bug Description:**
On importing a custom microtuning and keyboard mapping (attached as 31edo2.scl and 31edo2-subset.kbm) some keys have the incorrect mapped frequency. Most notably C4 shows up as 400 Hz which is a discontinuity compared to the keys either side of it. According to my calculations this key should be mapped to 200 Hz.

**Surge XT Version**
* Version: 1.3.2.f5bd0e1
* Plugin Type: Standalone
* Bitness: 64-bit

**Reproduction Steps:**
Steps to reproduce the behaviour:
1. Click on _Menu_
2. Go to _Tuning_ | _Load .scl tuning..._
3. Select `31edo2.scl` ([31edo2.scl.txt](https://github.com/user-attachments/files/17271948/31edo2.scl.txt))
4. Click on _Menu_
5. Go to _Tuning_ | _Load .kbm keyboard mapping..._
6. Select `31edo2-subset.scl` ([31edo2-subset.kbm.txt](https://github.com/user-attachments/files/17271950/31edo2-subset.kbm.txt))
7. Click on _Menu_
8. Go to _Tuning_ | _Open tuning editor..._

**Expected Behaviour:**
C4 should be mapped to 200 Hz. Here (
[surge-tuning-table.html.txt](https://github.com/user-attachments/files/17272004/surge-tuning-table.html.txt)) is the full tuning table exported as HTML. It's also possible that other mappings are incorrect but I have not exhaustively checked them. This ([scala-frequencies.txt](https://github.com/user-attachments/files/17272523/scala-frequencies.txt)) shows the frequencies generated by Scala for this scale and keyboard mapping.

**Screenshots:**
![Capture](https://github.com/user-attachments/assets/a201024c-6493-45f0-9915-3e32ee3004de)

If applicable, add screenshots/GIF/videos to help explain your problem.

**Computer Information (please complete the following!):**
 * OS: Windows 10
 * Host: Standalone

**Comment by baconpaul** [comment]
Thanks for posting both places! It will definitely be a fix here but let's discuss it over in the surge issue. I'll close both when i get the fix (probably today)
